name: Publish mkdocs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: pages-build-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: ruthkoole/algoritmekader-test@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
