name: Publish mkdocs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: pages-build-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
          
